package com.example.common.api;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESERVATION_NOT_FOUND,
    RESERVATION_NOT_PENDING,
    RESERVATION_ALREADY_EXISTS,
    INVENTORY_NOT_FOUND,
    INSUFFICIENT_STOCK,
    SKU_NOT_FOUND,
    MESSAGE_PROCESSING_FAILED,
    CONFLICT,
    INTERNAL_ERROR
}
